import type { Student } from './supabase';

const namesByClass: Record<string, string[]> = {
    'EMEJAALTE – Módulo II – N-A': [
        'ANA CLESSIA SALVINO ALVES', 'BRUNA OLIVEIRA DE CARVALHO', 'CARLA VIVIANE RODRIGUES DA SILVA',
        'DJORKAEFF MOURA SILVA', 'FRANK MARQUES MORAIS', 'HELOYSA DE AZEVEDO SOARES',
        'ISMAYK BRUNO DA SILVA CAMPOS', 'LAURICE CAMILA DOS SANTOS SILVA', 'PAMELLA COSTA SILVA',
        'WERIC GABRIEL SILVA SANTOS', 'WORBERT BANDEIRA DO NASCIMENTO'
    ],
    'EMTEJAINFO – Módulo II – N-A': [
        'ALINY MARIA DOS SANTOS SANTANA', 'ANA PAULA RODRIGUES MOURA',
        'ANNA VITORIA CHANTAL AZEVEDO SANTOS ROGERIO', 'CIBELE DE CARVALHO NASCIMENTO DA SILVA',
        'DHENNYFER EMILIA DA SILVA SOUSA', 'EDUARDA ABREU DOS SANTOS', 'ELIAS DA SILVA FORTES OLIVEIRA',
        'EVELLYN DE CARVALHO NASCIMENTO DA SILVA', 'FRANCISCA MARIA GOMES BARBOSA',
        'GILMARA SANTOS DA COSTA', 'IURY SOUZA ARAUJO', 'JARDEL SANTOS ARAUJO', 'KAUAN RODRIGUES DA SILVA',
        'KETLEY LORRANE PEREIRA DE SOUSA', 'KLAUDMILA LACERDA SILVA', 'LAIANE DE CARVALHO NASCIMENTO',
        'LÍVIA GABRIELLY FERREIRA NUNES NOGUEIRA', 'MARIA DOS REIS DE OLIVEIRA SANTOS',
        'MARIO LUIZ DA SILVA SANTOS', 'MISSILENE DE LAURENA', 'RAQUEL SAMARA PEREIRA DA SILVA',
        'RAYRA VITORIA DA ROCHA DE JESUS', 'RYAN WYLLYAN NUNES PEREIRA',
        'WELLINGTON JESUS DE SOUSA MAGALHÃES'
    ],
    'EMTEJAINFO – Módulo IV – N-A': [
        'AMADEU DAVID CORTEZ NUNES', 'ANA CAROLINA RODRIGUES DE SOUZA', 'ANA CRISTINA LIMA DE SOUSA',
        'BRENDA KALYNE FERREIRA DE OLIVEIRA', 'FELIPE DE OLIVEIRA ARAUJO', 'FLÁVIO WILLIAM SILVA SOUSA',
        'GUILHERME RODRIGUES DA SILVA GONCALVES', 'HENRY LUIS GOMES QUEIROZ SANTANA',
        'ISAMARA JOVITA ARAUJO TORRES', 'JACKSON DA COSTA SANTOS', 'JANA CLEA FERREIRA DE CARVALHO',
        'JOSE GONCALVES DE ARAUJO', 'LARISSA ANTONELA DA SILVA PACIFICO', 'LUIS CARLOS CRUZ SILVA',
        'MARCOS SILVA DE OLIVEIRA', 'MARIA ANTONIA VIEIRA DA SILVA RODRIGUES', 'MARIA ELIANE DE SOUSA',
        'MARIA VITORIA FREITAS GALVAO', 'SABRINA LIMA OLIVEIRA', 'SUZANA RAQUEL SANTOS SILVA',
        'THIAGO DANIEL DA SILVA PINTO'
    ],
    'EMTEJAINFO – Módulo IV – N-B': [
        'ADRIANA CONCEIÇÃO PEREIRA DE ALMEIDA', 'ALINE GONCALVES DE MELO', 'CARLA PATRICIA SOUSA OLIVEIRA',
        'ERLANE NASCIMENTO DE SOUSA', 'FRANCIMAURA DE SOUSA VELÔSO', 'FRANCISCA MARIA DOS SANTOS BRAGA',
        'GUILHERME DOS SANTOS BRITO', 'IASMIN ROCHA DOS SANTOS', 'ISADORA AGUIAR DOS SANTOS',
        'JOSÉ BALDOMIRO BEZERRA DE SOUSA', 'LUCAS SAMUEL DE SOUSA SILVA', 'MARIA DA GLORIA FERREIRA DÓRIA',
        'MARIA JAQUELINE PINHEIRO SILVA', 'MARIA RAMOS DO NASCIMENTO', 'MARLENE DE OLIVEIRA MORAES',
        'PEDRO HENRIQUE ALVES DA SILVA', 'RAILTON GABRIEL PEREIRA DOS SANTOS', 'TAMIRES SOUSA DOS SANTOS',
        'VANESSA ADRIELE SOARES DA SILVA'
    ],
    'EMTEJAMARK-DIG – Módulo II – N-A': [
        'ANA CAROLINY DOS SANTOS GOMES', 'ANGELINA FERREIRA DO NASCIMENTO', 'DANIEL DE ALMEIDA NERES',
        'DRIELI DA CONCEIÇÃO DE MORAIS', 'ELIANE PEREIRA LACERDA', 'FRANCIANE DA SILVA ALMEIDA',
        'FRANCIELLY YASMIM FERREIRA DE ANDRADE', 'FRANCISCO DAS CHAGAS ALMEIDA ALENCAR',
        'GLEYCIANE DA SILVA LOPES', 'GRAZIELLE DA LUZ VIEIRA', 'MARIA MILENA VIANA DA ROCHA',
        'MARIA DO SOCORRO SANTOS BRITO',
        'MARTA LAURA LOPES DE SOUSA', 'PALOMA CIBELY BRITO SILVA', 'RAFAEL DAMAS VIANA',
        'RAFAELA DA SILVA SANTOS', 'RAIMUNDO SOUSA SANTOS', 'REINALDO RIBEIRO DOS SANTOS'
    ]
};

export const getOfficialStudents = (className: string): Student[] =>
    (namesByClass[className] || []).map((name, index) => ({
        id: `official-${className}-${index + 1}`,
        name,
        class_id: className,
        active: true
    }));

export const OFFICIAL_STUDENT_COUNTS = Object.fromEntries(
    Object.entries(namesByClass).map(([className, names]) => [className, names.length])
);
