-- 📝 AJUSTE FINAL: TABELA DE FREQUÊNCIA (ef_attendance)
-- Este script recria a tabela para aceitar exatamente o que o App envia

-- 1. Remover a tabela antiga (CUIDADO: isso apaga frequências já registradas hoje)
DROP TABLE IF EXISTS ef_attendance;

-- 2. Criar a nova tabela com as colunas corretas
CREATE TABLE ef_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_name TEXT NOT NULL,
    discipline TEXT NOT NULL,
    class_name TEXT NOT NULL,
    student_name TEXT NOT NULL,
    status TEXT NOT NULL, -- 'present' ou 'absent'
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Habilitar Segurança (RLS)
ALTER TABLE ef_attendance ENABLE ROW LEVEL SECURITY;

-- 4. Criar Políticas de Acesso
DROP POLICY IF EXISTS "Leitura de Frequência" ON ef_attendance;
CREATE POLICY "Leitura de Frequência" ON ef_attendance FOR SELECT USING (true);

DROP POLICY IF EXISTS "Inserção de Frequência" ON ef_attendance;
CREATE POLICY "Inserção de Frequência" ON ef_attendance FOR INSERT WITH CHECK (true);

-- 5. Dar permissões de acesso
GRANT ALL ON ef_attendance TO anon, authenticated, service_role;

-- ✅ Tabela pronta para receber os dados do App!
