BEGIN;
TRUNCATE ef_schedule;
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD I A', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD I A', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD I A', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD I A', 'LÍNGUA PORTUGUESA', 'ALEXSANDRA MARIA LINARD PAES LANDIM');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD I A ALT', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD I A ALT', 'FÍSICA', 'EDNARDO FERREIRA DE SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD I A ALT', 'FÍSICA', 'EDNARDO FERREIRA DE SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD I A ALT', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD III A', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD III A', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD III A', 'REDES DE COMPUTADORES', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD III A', 'BANCO DE DADOS', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD III B', 'REDES DE COMPUTADORES', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD III B', 'REDES DE COMPUTADORES', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD III B', 'BANCO DE DADOS', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD III B', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD V A', 'PROGRAMAÇÃO DE SISTEMAS', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD V A', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD V A', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD V A', 'EMPREENDEDORISMO PARA TI', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD V B', 'ELETIVA', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD V B', 'PA I', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD V B', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD V B', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD V C', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD V C', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD V C', 'ELETIVA', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD V C', 'PA I', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD V D', 'PROGRAMAÇÃO DE SISTEMAS', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD V D', 'LÍNGUA PORTUGUESA', 'ALEXSANDRA MARIA LINARD PAES LANDIM');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD V D', 'LÍNGUA PORTUGUESA', 'ALEXSANDRA MARIA LINARD PAES LANDIM');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD V D', 'PROGRAMAÇÃO DE SISTEMAS', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 1, 'MOD I A MARK', 'FÍSICA', 'EDNARDO FERREIRA DE SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 2, 'MOD I A MARK', 'FDA', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 3, 'MOD I A MARK', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Segunda-feira', 4, 'MOD I A MARK', 'ELETIVA', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD I A', 'LÍNGUA PORTUGUESA', 'ALEXSANDRA MARIA LINARD PAES LANDIM');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD I A', 'LÍNGUA PORTUGUESA', 'ALEXSANDRA MARIA LINARD PAES LANDIM');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD I A', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD I A', 'FILOSOFIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD I A ALT', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD I A ALT', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD I A ALT', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD I A ALT', 'ED. FÍSICA A', 'CARLOS AUGUSTO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD III A', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD III A', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD III A', 'ELETIVA', 'PROFESSOR 1');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD III A', 'LOGICA DE PROGRAMAÇÃO', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD III B', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD III B', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD III B', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD III B', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD V A', 'SOCIOLOGIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD V A', 'ELETIVA', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD V A', 'EMPREENDEDORISMO PARA TI', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD V A', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD V B', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD V B', 'SOCIOLOGIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD V B', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD V B', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD V C', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD V C', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD V C', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD V C', 'LE', 'LINDELVÂNIA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD V D', 'LE', 'LINDELVÂNIA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD V D', 'ELETIVA', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD V D', 'SOCIOLOGIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD V D', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 1, 'MOD I A MARK', 'RPMD', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 2, 'MOD I A MARK', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 3, 'MOD I A MARK', 'LÍNGUA INGLESA', 'LINDELVÂNIA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Terça-feira', 4, 'MOD I A MARK', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD I A', 'LÍNGUA INGLESA', 'LINDELVÂNIA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD I A', 'INGLÊS INSTRUMENTAL', 'LINDELVÂNIA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD I A', 'ANAL. LÓG.', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD I A', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD I A ALT', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD I A ALT', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD I A ALT', 'FILOSOFIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD I A ALT', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD III A', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD III A', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD III A', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD III A', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD III B', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD III B', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD III B', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD III B', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD V A', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD V A', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD V A', 'LE', 'ELLYDA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD V A', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD V B', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD V B', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD V B', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD V B', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD V C', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD V C', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD V C', 'EMPREENDEDORISMO PARA TI', 'LUCIANO DE OLIVEIRA CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD V C', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD V D', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD V D', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD V D', 'FÍSICA', 'JORGE LUÍS SÁ BEZERRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD V D', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'JARBAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 1, 'MOD I A MARK', 'MATEMÁTICA', 'GEMILSON');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 2, 'MOD I A MARK', 'IAM', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 3, 'MOD I A MARK', 'PROJETO DE APRENDIZAGEM INTERDISCIPLINAR', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quarta-feira', 4, 'MOD I A MARK', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD I A', 'ANAL. LÓG.', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD I A', 'ED. FÍSICA A', 'CARLOS AUGUSTO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD I A', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD I A', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD I A ALT', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD I A ALT', 'QUÍMICA', 'FRANCISCO JR');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD I A ALT', 'QUÍMICA', 'FRANCISCO JR');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD I A ALT', 'PROJETO DE VIDA', 'FRANCISCO JR');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD III A', 'BANCO DE DADOS', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD III A', 'REDES DE COMPUTADORES', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD III A', 'LOGICA DE PROGRAMAÇÃO', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD III A', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD III B', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD III B', 'BANCO DE DADOS', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD III B', 'LOGICA DE PROGRAMAÇÃO', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD III B', 'LOGICA DE PROGRAMAÇÃO', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD V A', 'PROGRAMAÇÃO DE SISTEMAS', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD V A', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD V A', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD V A', 'PROGRAMAÇÃO DE SISTEMAS', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD V B', 'LE', 'ELLYDA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD V B', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD V B', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD V B', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD V C', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD V C', 'LÍNGUA PORTUGUESA', 'FRANCINEUDA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD V C', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD V C', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD V D', 'PROGRAMAÇÃO DE SISTEMAS', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD V D', 'HISTÓRIA', 'FRANCISCA DA SILVA SOUSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD V D', 'EMPREENDEDORISMO PARA TI', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD V D', 'EMPREENDEDORISMO PARA TI', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 1, 'MOD I A MARK', 'RPMD', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 2, 'MOD I A MARK', 'TAVDA', 'GERSON DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 3, 'MOD I A MARK', 'ED. FÍSICA A', 'CARLOS AUGUSTO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Quinta-feira', 4, 'MOD I A MARK', 'BIOLOGIA', 'HELANNE BEATRIZ SILVA OLIVEIRA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD I A', 'INFORMA TICA APLICADA A', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD I A', 'INFORMA TICA APLICADA A', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD I A', 'ELETIVA', 'DENILSON DAVID DA SILVA SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD I A', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD I A ALT', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD I A ALT', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD I A ALT', 'ARTE', 'JOANA DARC');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD I A ALT', 'LÍNGUA INGLESA', 'CARMEN');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD III A', 'ARTE', 'JOANA DARC');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD III A', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD III A', 'LÍNGUA INGLESA', 'CARMEN');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD III A', 'FILOSOFIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD III B', 'FILOSOFIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD III B', 'LÍNGUA INGLESA', 'CARMEN');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD III B', 'ELETIVA', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD III B', 'ARTE', 'JOANA DARC');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD V A', 'EMPREENDEDORISMO PARA TI', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD V A', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD V A', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD V A', 'PROGRAMAÇÃO DE SISTEMAS', 'MARCOS AURELIO MATOS DOS SANTOS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD V B', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD V B', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD V B', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD V B', 'PROGRAMAÇÃO DE SISTEMAS', 'HORÁRIO VAGO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD V C', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD V C', 'SOCIOLOGIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD V C', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD V C', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD V D', 'MATEMÁTICA', 'WESLEY BEZERRA PORTELA FREITAS');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD V D', 'PROGRAMAÇÃO DE SISTEMAS', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD V D', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD V D', 'EMPREENDEDORISMO PARA TI', 'SALOMÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 1, 'MOD I A MARK', 'QUÍMICA', 'WILSILENE DOS SANTOS OLIVEIRA BRANDÃO');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 2, 'MOD I A MARK', 'LÍNGUA PORTUGUESA', 'MARIA EUNICE LIRA TEIXEIRA ANDRADE');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 3, 'MOD I A MARK', 'FILOSOFIA', 'DANIEL MAGALHAES CHAVES');
INSERT INTO ef_schedule (day_of_week, slot_number, class_group, discipline, teacher_name) VALUES ('Sexta-feira', 4, 'MOD I A MARK', 'GEOGRAFIA', 'JOSE DE ASSUNCAO SOUSA BARBOSA');
COMMIT;